# Generated by Django 6.0.4 on 2026-04-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('ar', 'Arabic')], default='en', max_length=5)),
                ('full_name', models.CharField(max_length=200)),
                ('english_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('role_responsibilities', models.JSONField(blank=True, default=dict)),
                ('workflow_efficiency', models.JSONField(blank=True, default=dict)),
                ('pain_points', models.JSONField(blank=True, default=dict)),
                ('communication', models.JSONField(blank=True, default=dict)),
                ('tools_technology', models.JSONField(blank=True, default=dict)),
                ('ideas_suggestions', models.JSONField(blank=True, default=dict)),
                ('consent_given', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='idcards/')),
            ],
            options={
                'verbose_name': 'Employee Submission',
                'verbose_name_plural': 'Employee Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
